dist: bionic

addons:
  apt:
    update: true  
    packages:
    - devscripts
    - equivs
    - pandoc
    - jq

env:
  - POSTGRESQL_VERSION=9.4
  - POSTGRESQL_VERSION=9.5
  - POSTGRESQL_VERSION=10
  - POSTGRESQL_VERSION=11

before_install:
  # Switch to active PostGre version
  - sudo /etc/init.d/postgresql stop
  - sudo service postgresql start $POSTGRESQL_VERSION
  
  # Install more tools
  - npm install -g csvtojson
  - npm install -g mustache
  
  # - for i in ${TRAVIS_BUILD_DIR}/src/*.csv; do csvtojson $i > $i.json; done
  # - for i in ${TRAVIS_BUILD_DIR}/src/*.csv.json; do cat $i; done
  # - for i in ${TRAVIS_BUILD_DIR}/src/*.csv.json; do jq $i > $i; done
  # - jq "[file_name]" ${TRAVIS_BUILD_DIR}/src/*.csv.json
  - cd ${TRAVIS_BUILD_DIR}/src
  - mustache test.json street_abbrv.mustache.sql

install:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo mk-build-deps -i debian/control
  
  - pg_lsclusters
  - sudo pg_lsclusters
  - pg_config --sharedir
  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 gis

  - cd ${TRAVIS_BUILD_DIR}
  - sudo make install

  - psql --dbname=gis --command="CREATE EXTENSION osmabbrv"

script:
  - cd ${TRAVIS_BUILD_DIR}/tests
  - ./runtests_pgsql.sh gis
