dist: bionic

env:
  global:
    - PGPORT=5433

addons:
  # postgresql: 11
  apt:
    update: true  
    packages:
    - devscripts
    - equivs
    - libkakasi2-dev
    - libutf8proc-dev
    - pandoc
    - postgis
    - postgresql-plpython3-11

before_install:
  - sudo mk-build-deps -i debian/control

  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 gis
  - psql --dbname=gis --command="CREATE EXTENSION fuzzystrmatch"
  - psql --dbname=gis --command="CREATE EXTENSION unaccent"
  - psql --dbname=gis --command="CREATE EXTENSION postgis"
  - psql --dbname=gis --command="CREATE EXTENSION hstore"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo make install
  - psql --dbname=gis --command="CREATE EXTENSION osmabbrv"

script:
  - cd ${TRAVIS_BUILD_DIR}/tests
  - ./runtests.sh gis
