dist: bionic

addons:
  postgresql: '10'
  apt:
    update: true  
    packages:
    - devscripts
    - equivs
    - pandoc
    # - postgresql-10-postgis-2.4
    - jq

before_install:
  - npm install -g csvtojson
  - npm install -g mustache
  - cd ${TRAVIS_BUILD_DIR}/src
  - mustache test.json street_abbrv.mustache.sql

install:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo mk-build-deps -i debian/control
  
  - pg_lsclusters

  - pg_config --sharedir
  - sudo pg_config --sharedir
  - sudo -u postgres pg_config --sharedir
  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 gis

  - cd ${TRAVIS_BUILD_DIR}
  - mkdir gen
  - make -np all
  # - make -nd all
  - make all
  - ls -ltra gen
  - cat gen/*.json
  - cat gen/*.sql
    
  - sudo make install
  - ls -ltra /usr/share/postgresql/10/extension
  - psql --dbname=gis --command="CREATE EXTENSION osmabbrv"

script:
  - cd ${TRAVIS_BUILD_DIR}/tests
  - ./runtests_pgsql.sh gis
