dist: bionic

addons:
  postgresql: '10'
  apt:
    update: true  
    packages:
    - devscripts
    - equivs
    - pandoc
    - postgresql-10-postgis-2.4
    - jq

before_install:
  - npm install -g csvtojson
  - npm install -g mustache
  - csvtojson ${TRAVIS_BUILD_DIR}/src/de_tests.csv > ${TRAVIS_BUILD_DIR}/src/de_tests.json
  - csvtojson ${TRAVIS_BUILD_DIR}/src/fr_tests.csv > ${TRAVIS_BUILD_DIR}/src/fr_tests.json
  - jq "." ${TRAVIS_BUILD_DIR}/src/de_tests.json ${TRAVIS_BUILD_DIR}/src/fr_tests.json
  - csvtojson ${TRAVIS_BUILD_DIR}/src/*_tests.csv
  - mustache ${TRAVIS_BUILD_DIR}/src/test.json ${TRAVIS_BUILD_DIR}/src/street_abbrv.mustache.sql

install:
  - sudo mk-build-deps -i debian/control
  
  - pg_lsclusters

  - pg_config --sharedir
  - sudo pg_config --sharedir
  - sudo -u postgres pg_config --sharedir

  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 gis
  - psql --dbname=gis --command="CREATE EXTENSION fuzzystrmatch"
  - psql --dbname=gis --command="CREATE EXTENSION unaccent"
  - psql --dbname=gis --command="CREATE EXTENSION postgis"
  - psql --dbname=gis --command="CREATE EXTENSION hstore"

  - cd ${TRAVIS_BUILD_DIR}
  - sudo make install
  - ls -ltra /usr/share/postgresql/10/extension
  - psql --dbname=gis --command="CREATE EXTENSION osmabbrv"

script:
  - cd ${TRAVIS_BUILD_DIR}/tests
  - ./runtests_pgsql.sh gis
