dist: bionic

addons:
  postgresql: '10'
  apt:
    update: true  
    packages:
    - devscripts
    - equivs
    - pandoc
    - postgis

install:
  - sudo mk-build-deps -i debian/control
  
  - pg_lsclusters
  - sudo -u postgres createuser travis
  - sudo -u postgres createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 gis
  - psql --dbname=gis --command="CREATE EXTENSION fuzzystrmatch"
  - psql --dbname=gis --command="CREATE EXTENSION unaccent"
  - psql --dbname=gis --command="CREATE EXTENSION postgis"
  - psql --dbname=gis --command="CREATE EXTENSION hstore"

  - cd ${TRAVIS_BUILD_DIR}
  - sudo make install
  - psql --dbname=gis --command="CREATE EXTENSION osmabbrv"

script:
  - cd ${TRAVIS_BUILD_DIR}/tests
  - ./runtests.sh gis
